/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.beingzero.paint;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

/**
 *
 * @author karthik-pc
 */
public class PaintGUI extends javax.swing.JFrame implements MouseListener{
            ArrayList<IShape> shapes;
            Shape currentShape;
    /**
     * Creates new form PaintGUI
     */
    public PaintGUI() {
        initComponents();
        shapes = new ArrayList<IShape>();
        panel.addMouseListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgShape = new javax.swing.ButtonGroup();
        btnOval = new javax.swing.JRadioButton();
        btnRect = new javax.swing.JRadioButton();
        btnLine = new javax.swing.JRadioButton();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgShape.add(btnOval);
        btnOval.setText("Oval");

        bgShape.add(btnRect);
        btnRect.setText("Rectangle");

        bgShape.add(btnLine);
        btnLine.setText("Line");

        panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnOval)
                        .addGap(18, 18, 18)
                        .addComponent(btnRect)
                        .addGap(18, 18, 18)
                        .addComponent(btnLine))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOval)
                    .addComponent(btnRect)
                    .addComponent(btnLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaintGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgShape;
    private javax.swing.JRadioButton btnLine;
    private javax.swing.JRadioButton btnOval;
    private javax.swing.JRadioButton btnRect;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    public void mouseClicked(MouseEvent e) {
        System.out.printf("[Clicked] %d ,%d \n", e.getX(), e.getY());
        
    }

    public void mousePressed(MouseEvent e) {
                System.out.printf("[Pressed] %d ,%d \n", e.getX(), e.getY());
                if(btnOval.isSelected())
                currentShape =new Oval();
                else if(btnLine.isSelected())
                    currentShape = new Line();
                else
                    currentShape = new Rectangle();
                currentShape.x1 = e.getX();
                currentShape.y1 = e.getY();

    }

    public void mouseReleased(MouseEvent e) {
                System.out.printf("[Released] %d ,%d \n", e.getX(), e.getY());
                currentShape.x2 =e.getX();
                currentShape.y2 = e.getY();
                currentShape.draw(panel.getGraphics());
               
                

    }

    public void mouseEntered(MouseEvent e) {
                System.out.printf("[Entered] %d ,%d \n", e.getX(), e.getY());

    }

    public void mouseExited(MouseEvent e) {
                System.out.printf("[Exited] %d ,%d \n", e.getX(), e.getY());
                panel.repaint();

    }
}
